### ISSUE TITLE
Splat Viewer

### ISSUE THREAD

**Issue by mgs823** [joblobob/polyrhythm#1]
你好，我看到了你在Splat Viewer做的一些改进基于antimatter15/splat，不知道你是否取得了一些令人惊叹的进展，由于你的那个项目没有issue，所以我在这里提问，如果给你带来困扰，抱歉，如果你有一些进展，期待你的分享
Hello, I have seen some improvements you have made in Splat Viewer based on antimatter15/splat. I am not sure if you have made any amazing progress. As your project has not been issued, I am here to ask a question. If this has caused you any inconvenience, I apologize. If you have any progress, I look forward to your sharing

**Comment by joblobob** [comment]
Hello! Yes, I have made some progress as I have translated the code from javascript to C++ to make it work in a standalone app. I'll then use C++23 features to prepare a talk based on it at the CppNorth 2024 in Toronto. For the moment, the issues I have are glitches with intel integrated graphics card, maybe there are too much data! hehe!

**Comment by joblobob** [comment]
I'm closing this issue and move it to the real code repo
